package com.nas_inc.quizapplication;

import java.util.ArrayList;
import java.util.List;

public class QuestionsBank {
    private static List<ListOfQuestions> javaQuestions() {

        final List<ListOfQuestions> questionsLists = new ArrayList<>();

        //Create object of ListOfQuestions class and pass a questions along with alternatives and answer
        final ListOfQuestions question1 = new ListOfQuestions("Which of the following packages is automatically loaded, so you don’t need to import it?","java.util", "javax.swing", "java.math", "java.lang", "java.lang", "");
        final ListOfQuestions question2 = new ListOfQuestions("To what object-oriented programming concept does the java keyword private apply?", "Polymorphism", "Inheritance", "Encapsulation", "Overriding", "Overriding", "");
        final ListOfQuestions question3 = new ListOfQuestions("What is the use of ‘javac’ command?", "Execute a java program", "Debug a java program", "Interpret a java program", "Compile a java program", "Compile a java program", "");
        final ListOfQuestions question4 = new ListOfQuestions("Parent class of all java classes is?", "java.lang.system", "java.lang.object", "java.lang.class", "java.lang,reflect.object", "java.lang.object", "");
        final ListOfQuestions question5 = new ListOfQuestions("Which of the following is NOT a java primitive type", "short", "long", "long double", "boolean", "long double", "");
        final ListOfQuestions question6 = new ListOfQuestions("A condition that is caused by run-time error in a computer program is known as?", "syntax error", "fault", "semantic error", "exception", "exception", "");
        final ListOfQuestions question7 = new ListOfQuestions("Number of primitive data types in Java are?", "6", "7", "8", "9", "8", "");
        final ListOfQuestions question8 = new ListOfQuestions("On which platforms Java runs?", "Windows", "Mac OS", "UNIX", "All of these", "All of these", "");
        final ListOfQuestions question9 = new ListOfQuestions("Select Odd one out from these about local variables", "Local variables are declared in methods, constructors, or blocks", "Local variables are created when the method, constructor or block is entered", "the variable will be destroyed once it exits the method, constructor, or block", "We can't create reference variables of Local variables", "We can't create reference variables of Local variables", "");
        final ListOfQuestions question10 = new ListOfQuestions("Which one of the following is Equality operator in Java?", ">=", "<=", "!=", "+=", "!=", "");
        final ListOfQuestions question11 = new ListOfQuestions("Which one of the following is an Unary operator in Java?", "()", "*", "+", "++", "++", "");
        final ListOfQuestions question12 = new ListOfQuestions("Who is known as father of Java programming language", "James Gosling", "Charel Babbage", "M. P Java", "Blais Pascal", "James Gosling", "");
        final ListOfQuestions question13 = new ListOfQuestions("In java control statements break, continue, return, try-catch-finally and assert belongs to?", "Selection statements", "Loop statements", "Transfer statements", "Pause statement", "Transfer statements", "");
        final ListOfQuestions question14 = new ListOfQuestions("Which provides runtime environment for java byte code to be executed", "JDK", "JVM", "JRE", "JAVAC", "JVM", "");
        final ListOfQuestions question15 = new ListOfQuestions("What is byte code in Java?", "Code generated by a Java compiler", "Code generated by a JVM", "Name of Java source code file", "Block of code written inside a class", "Code generated by a Java compiler", "");


        //add all questions to List<ListOfQuestions>
        questionsLists.add(question1);
        questionsLists.add(question2);
        questionsLists.add(question3);
        questionsLists.add(question4);
        questionsLists.add(question5);
        questionsLists.add(question6);
        questionsLists.add(question7);
        questionsLists.add(question8);
        questionsLists.add(question9);
        questionsLists.add(question10);
        questionsLists.add(question11);
        questionsLists.add(question12);
        questionsLists.add(question13);
        questionsLists.add(question14);
        questionsLists.add(question15);

        return questionsLists;
    }

    private static List<ListOfQuestions> nursingQuestions() {

        final List<ListOfQuestions> questionsLists = new ArrayList<>();

        //Create object of ListOfQuestions class and pass a questions along with alternatives and answer
        final ListOfQuestions question1 = new ListOfQuestions("What needs of a patient does a nurse address?", "Physical", "Emotional", "Mental", "All of the above", "All of the above", "");
        final ListOfQuestions question2 = new ListOfQuestions("The nursing care plan for a client with decreased adrenal function should include?", "Encouraging activity", "Placing client in reverse isolation", "Limiting visitors", "Measures to prevent constipation", "Limiting visitors", "");
        final ListOfQuestions question3 = new ListOfQuestions("The first case of Covid positive case in India reported in?", "Kerala", "Tamilnadu", "Gujarat", "Maharashtra", "Kerala", "");
        final ListOfQuestions question4 = new ListOfQuestions("The epithelial tissue which is found in the uterine tubes is?", "Squamous", "Ciliated", "Columnar", "Simple", "Ciliated", "");
        final ListOfQuestions question5 = new ListOfQuestions("The part of the fetus which occupies the lower pole of the uterus is called?", "Lie", "Presentation", "Denominator", "Position", "Presentation", "");
        final ListOfQuestions question6 = new ListOfQuestions("Low levels of maternal serum alpha-fetoprotein levels are found in?", "Open neural tube defect", "Down syndrome", "Multiple pregnancies", "Rh-isoimmunisation", "Down syndrome", "");
        final ListOfQuestions question7 = new ListOfQuestions("The total lung capacity in a healthy adult male is approximate?", "500 ml", "5000 mL", "6000 mL", "6000 L", "6000 L", "");
        final ListOfQuestions question8 = new ListOfQuestions("The ideal roller bandage application for body parts where the thickness varies, such as over the forearm, is?", "Simple spiral", "Figure of eight", "Reverse spiral", "Divergent spica", "Reverse spiral", "");
        final ListOfQuestions question9 = new ListOfQuestions("The external rotation of the hip in the supine position, is prevented by using?", "Bed cradle", "Bedboard", "Trochanter roll", "Knee rest", "Trochanter roll", "");
        final ListOfQuestions question10 = new ListOfQuestions("A simple and cost-effective method for reducing the risk of hypostatic pneumonia in a bedridden patient is?", "Antibiotics", "Nebulization", "Frequent change of positions", "Humidified oxygen", "Frequent change of positions", "");
        final ListOfQuestions question11 = new ListOfQuestions("Which among the following is an example of an isotonic intravenous solution?", "Dextrose normal saline", "10% Detrose", "0.45% NaCl", "Ringer's Lactate", "Ringer's Lactate", "");
        final ListOfQuestions question12 = new ListOfQuestions("WHO declared the 2019-novel Coronavirus outbreak as a Public Health Emergency of International Concern (PHEIC) on?", "January 30, 2020", "January 13, 2020","January 23, 2020","January 27, 2020", "January 30, 2020", "");
        final ListOfQuestions question13= new ListOfQuestions("First death due to COVID was reported in which district in Kerala?", "Kasaragod","Ernakulam", "Trivandrum", "Malappuram", "Ernakulam", "");
        final ListOfQuestions question14 = new ListOfQuestions("Which of the following cells of the body are in almost constant mitosis?", "Nerve cells", "Stomach cells", "Muscle cells", "Renal cells", "Stomach cells", "");
        final ListOfQuestions question15 = new ListOfQuestions("Which of the following people have the largest percentage of water in their bodies?", "Fat men", "Lean men", "Lean women", "Fat women", "Lean men", "");

        //add all questions to List<ListOfQuestions>
        questionsLists.add(question1);
        questionsLists.add(question2);
        questionsLists.add(question3);
        questionsLists.add(question4);
        questionsLists.add(question5);
        questionsLists.add(question6);
        questionsLists.add(question7);
        questionsLists.add(question8);
        questionsLists.add(question9);
        questionsLists.add(question10);
        questionsLists.add(question11);
        questionsLists.add(question12);
        questionsLists.add(question13);
        questionsLists.add(question14);
        questionsLists.add(question15);

        return questionsLists;
    }

    private static List<ListOfQuestions> sociologyQuestions() {

        final List<ListOfQuestions> questionsLists = new ArrayList<>();

        //Create object of ListOfQuestions class and pass a questions along with alternatives and answer
        final ListOfQuestions question1 = new ListOfQuestions("The term ‘sociology’ was coined by", "Saint Simon", "Herbert Spencer", "Auguste Comte", "Durkheim", "Auguste Comte", "");
        final ListOfQuestions question2 = new ListOfQuestions("In which year the term ‘Sociology’ was coined?", "1798", "1815", "1839", "1857", "1839", "");
        final ListOfQuestions question3 = new ListOfQuestions("French Revolution took place in the year?", "1789", "1776", "1798", "1898", "1789", "");
        final ListOfQuestions question4 = new ListOfQuestions("Sociology emerged in?", "America", "Europe", "Asia", "Africa", "Europe", "");
        final ListOfQuestions question5 = new ListOfQuestions("The word ‘Sociology’ is made up of two words. These are...", "Societies and Logy", "Societia and Logistia", "Socious and Logos", "Socia and Logos", "Socious and Logos", "");
        final ListOfQuestions question6 = new ListOfQuestions("Society emerges out of?", "Community's existence", "Men's existence", "Problem's existence", "Relationship", "Men's existence", "");
        final ListOfQuestions question7 = new ListOfQuestions("Society symbolises the network of?", "Human relationships","Social relationships", "Orientations", "Inter-connections", "Social relationships", "");
        final ListOfQuestions question8 = new ListOfQuestions("There are two types of definition of society. These are...", " Structural and interactional", "Functional and structural", "Evolutionary and diffusive","Structural and evolutionary", "Functional and structural", "");
        final ListOfQuestions question9 = new ListOfQuestions("Society is", "Natural", "Deliberate", "Practical", "Functional", "Deliberate", "");
        final ListOfQuestions question10 = new ListOfQuestions("Marriage is considered to be necessary because?", "This is the only way to acquire paternal property", "This is the only way of sexual gratification", "This provides societal sanction", "It is regularised and provides socially sanctioned sex gratification","It is regularised and provides socially sanctioned sex gratification", "");
        final ListOfQuestions question11 = new ListOfQuestions("Who among the following was on the opinion that 'A gift is a social substitute for money among moneyless cultures'?", "Ogburn and Nimkoff", "Mauss", "Frazer", "Polyan", "Ogburn and Nimkoff", "");
        final ListOfQuestions question12 = new ListOfQuestions("The basis of slave system is always?", "Political", "Economic", "Custom", "Social need", "Economic", "");
        final ListOfQuestions question13 = new ListOfQuestions("A characteristic feature of a rural community is?", "Formal relationship", "Rational will", "Community sentiment", "A vast number of association", "Formal relationship", "");
        final ListOfQuestions question14 = new ListOfQuestions("Who among the following was the first to distinquish between the state and the government?", "Locke", "R. Dahl", "Marx", "Max Weber", "Locke", "");
        final ListOfQuestions question15 = new ListOfQuestions("Demographers do not take into account?", "Age, sex and racial composition of the population", "Height and weight of the population", "Birth and death rate", "Density of population", "Height and weight of the population", "");

        //add all questions to List<ListOfQuestions>
        questionsLists.add(question1);
        questionsLists.add(question2);
        questionsLists.add(question3);
        questionsLists.add(question4);
        questionsLists.add(question5);
        questionsLists.add(question6);
        questionsLists.add(question7);
        questionsLists.add(question8);
        questionsLists.add(question9);
        questionsLists.add(question10);
        questionsLists.add(question11);
        questionsLists.add(question12);
        questionsLists.add(question13);
        questionsLists.add(question14);
        questionsLists.add(question15);

        return questionsLists;
    }

    private static List<ListOfQuestions> physicsQuestions() {

        final List<ListOfQuestions> questionsLists = new ArrayList<>();

        //Create object of ListOfQuestions class and pass a questions along with alternatives and answer
        final ListOfQuestions question1 = new ListOfQuestions("Which of the following measurements is not a unit of distance?", "Ammeter", "Cubit", "Parsec", "angstrom", "Ammeter", "");
        final ListOfQuestions question2 = new ListOfQuestions("Which one of the following remains constant while throwing a ball upward?", "Displacement", "Kinetic Energy", "Acceleration", "Velocity", "Acceleration", "");
        final ListOfQuestions question3 = new ListOfQuestions("Pure water freezes at what temperature?", "47F", "32F", "0F", "19F", "32F", "");
        final ListOfQuestions question4 = new ListOfQuestions("Zinc Oxide is?", "Acidic", "Basic", "Neutral", "Amphoteric", "Amphoteric", "");
        final ListOfQuestions question5 = new ListOfQuestions("Pure water is a ______ conductor of electricity.", "super", "bad", "speed", "None of these", "bad", "");
        final ListOfQuestions question6 = new ListOfQuestions("What element’s three isotopes have different names?", "Helium", "Oxygen","Carbon", "Hydrogen", "Hydrogen", "");
        final ListOfQuestions question7 = new ListOfQuestions("On which on of the following conservation laws does a rocket work?", "Mass", "Energy", "Linear momentum", "Angular momentum", "Linear momentum", "");
        final ListOfQuestions question8 = new ListOfQuestions("Which one among the following radiations carries maximum energy", "Ultraviolet rays", "Gamma rays", "X-rays", "Infra red rays", "Gamma rays", "");
        final ListOfQuestions question9 = new ListOfQuestions("What is the main constituent of coal gas?", "Oxygen", "Water", "Nitrogen", "Methane", "Nitrogen", "");
        final ListOfQuestions question10 = new ListOfQuestions("Recoil of a gun is an example of?", "Conservation of mass", "Conservation of energy", "Conservation into KE", "Conservation of linear momentum", "Conservation of linear momentum", "");
        final ListOfQuestions question11 = new ListOfQuestions("What is the heaviest of the naturally occurring Noble gases?", "Radon", "Xenon", "Helium", "Argon", "Radon", "");
        final ListOfQuestions question12 = new ListOfQuestions("Aviation fuel for Jet aero planes consists of purified", "Petrol", "Kerosene", "Gasoline", "Diesel", "Kerosene", "");
        final ListOfQuestions question13 = new ListOfQuestions("A piece of stone or iron travelling through space that moves through the earth's atmosphere is?", "Planet", "Sun", "Moon", "Meteor", "Meteor", "");
        final ListOfQuestions question14 = new ListOfQuestions("Mesons are found in?", "Alpha-rays", "Laser beam", "X-rays", "Cosmic rays", "Cosmic rays", "");
        final ListOfQuestions question15 = new ListOfQuestions("The wavelength of X-rays is of the order of?", "1 cm", "1 m", "10 micron", "1 Angstrom", "1 Angstrom", "");

        //add all questions to List<ListOfQuestions>
        questionsLists.add(question1);
        questionsLists.add(question2);
        questionsLists.add(question3);
        questionsLists.add(question4);
        questionsLists.add(question5);
        questionsLists.add(question6);
        questionsLists.add(question7);
        questionsLists.add(question8);
        questionsLists.add(question9);
        questionsLists.add(question10);
        questionsLists.add(question11);
        questionsLists.add(question12);
        questionsLists.add(question13);
        questionsLists.add(question14);
        questionsLists.add(question15);

        return questionsLists;
    }

    private static List<ListOfQuestions> civilEngineeringQuestions() {

        final List<ListOfQuestions> questionsLists = new ArrayList<>();

        //Create object of ListOfQuestions class and pass a questions along with alternatives and answer
        final ListOfQuestions question1 = new ListOfQuestions("The rocks formed from molten magma are called?", "sedimentary rocks", "igneous rocks", "metamorphic rocks", "none of these", "igneous rocks", "");
        final ListOfQuestions question2 = new ListOfQuestions("The rocks formed by gradual deposition are called?", "sedimentary rocks", "igneous rocks", "metamorphic rocks", "none of these", "sedimentary rocks", "");
        final ListOfQuestions question3 = new ListOfQuestions("The curvature of the earth's surface, is taken into account only if the extent of survey is more than?", "100 sq km", "160 sq km", "200 sq km", "260 sq km", "260 sq km", "");
        final ListOfQuestions question4 = new ListOfQuestions("Hydrographic surveys deal with the mapping of?", "large water bodies", "heavenly bodies", "mountainous region", "canal system", "large water bodies", "");
        final ListOfQuestions question5 = new ListOfQuestions("The distance between the centers of adjacent rivets in the same row is called?", "pitch", "lap", "gauge", "staggered pitch", "pitch", "");
        final ListOfQuestions question6 = new ListOfQuestions("Failure of riveted joints is due to?", "Tearing of the plates b/n the edge of the plate", "Tearing of plates b/n rivets","Shearing of rivets", "All the above", "All the above", "");
        final ListOfQuestions question7 = new ListOfQuestions("The strength and quality of concrete, depend upon?", "grading of aggregates", "surface area of aggregates", "shape of aggregates", "all the above", "all the above", "");
        final ListOfQuestions question8 = new ListOfQuestions("To hydrate 500kg cement fully, water needed is?", "100kg", "110kg", "120kg", "130kg", "130kg", "");
        final ListOfQuestions question9 = new ListOfQuestions("A concrete having a slump of 65cm is said to be?", "dry", "earth moist", "semi-plastic", "plastic", "plastic", "");
        final ListOfQuestions question10 = new ListOfQuestions("Concrete is unsuitable for compaction by a vibrator if it is?", "dry", "earth moist","semi-plastic", "plastic", "plastic", "");
        final ListOfQuestions question11 = new ListOfQuestions("The increased cohesiveness of concrete makes it?", "less liable to segregation", "more liable to segregation", "more liable to bleeding", "more liable for surface scaling in frosty weather", "less liable to segregation", "");
        final ListOfQuestions question12 = new ListOfQuestions("After casting, an ordinary cement concrete on drying...", "expands", "shrinks", "evaporates", "none of these", "shrinks", "");
        final ListOfQuestions question13 = new ListOfQuestions("To produce impermeable concrete?", "thorough mixing of concrete is required", "proper compaction of concrete is required", "proper curing of concrete is required", "all the above", "all the above", "");
        final ListOfQuestions question14 = new ListOfQuestions("Separation of coarse aggregates from mortar during transportation is known as?", "bleeding", "creeping", "segregation", "shrinkage", "segregation", "");
        final ListOfQuestions question15 = new ListOfQuestions("Concrete mainly consists of?", "cement", "aggregates", "admixture", "all the above", "all the above", "");

        //add all questions to List<ListOfQuestions>
        questionsLists.add(question1);
        questionsLists.add(question2);
        questionsLists.add(question3);
        questionsLists.add(question4);
        questionsLists.add(question5);
        questionsLists.add(question6);
        questionsLists.add(question7);
        questionsLists.add(question8);
        questionsLists.add(question9);
        questionsLists.add(question10);
        questionsLists.add(question11);
        questionsLists.add(question12);
        questionsLists.add(question13);
        questionsLists.add(question14);
        questionsLists.add(question15);

        return questionsLists;
    }

    private static List<ListOfQuestions> farmingQuestions() {

        final List<ListOfQuestions> questionsLists = new ArrayList<>();

        //Create object of ListOfQuestions class and pass a questions along with alternatives and answer
        final ListOfQuestions question1 = new ListOfQuestions("Primary resources for agriculture are?", "Land, air and water", "Seed, Fertilizer and Pesticide", "Seed, air and water", "Land, Fertilizer and water", "Land, air and water", "");
        final ListOfQuestions question2 = new ListOfQuestions("For the cultivation of Tobacco the soil should be rich in?", "Calcareous matter", "Nitrogen", "Organic Content", "Potash", "Potash", "");
        final ListOfQuestions question3 = new ListOfQuestions("Rice is which kind of crop?", "Autumn", "Evergreen", "Fall", "Monsoon", "Monsoon", "");
        final ListOfQuestions question4 = new ListOfQuestions("Cultivation involving slash and burn?", "Shifting cultivation", "Nomadic herding", "Mixed farming", "Plantation", "Shifting cultivation", "");
        final ListOfQuestions question5 = new ListOfQuestions("Potato and tomato are native of?", "Canada", "North America", "China", "South America", "South America", "");
        final ListOfQuestions question6 = new ListOfQuestions("Which of the following is suitable for growing cotton?", "Sandy soil", "Clayey soil","Black soil", "Alluvial soil", "Black soil", "");
        final ListOfQuestions question7 = new ListOfQuestions("Requires 210 frost free days for growth?", "rice", "wheat", "maize", "cotton", "cotton", "");
        final ListOfQuestions question8 = new ListOfQuestions("Soil acidity is generally corrected by?", "proper irrigation", "adding sodium hydrogen", "liming", "application of fertilizers", "liming", "");
        final ListOfQuestions question9 = new ListOfQuestions("The cotton crop field rotation is?", "Four yearly", "Three yearly", "Half yearly", "Two yearly", "Four yearly", "");
        final ListOfQuestions question10 = new ListOfQuestions("Which of the following is a root?", "Onion", "Carrot", "Potato", "Ginger", "Carrot", "");
        final ListOfQuestions question11 = new ListOfQuestions("Rearing of animals for sale is?", "Nomadic herding", "Shifting", "Intensive farming", "Commercial farming", "Commercial farming", "");
        final ListOfQuestions question12 = new ListOfQuestions("Which disease is more common among agricultural workers as compared to urban population?", "Cancer", "Cirrhosis of liver", "Lung disease", "Hookworm infection", "Hookworm infection", "");
        final ListOfQuestions question13 = new ListOfQuestions("Which one of the following practices is adopted for restoring the fertility of soil?", "Weeding", "Levelling", "Fallowing", "Harrowing", "Fallowing", "");
        final ListOfQuestions question14 = new ListOfQuestions("Why is wheat flour useful in baking bread? It is due to the higher content of...", "Starch", "Sugar", "Protein", "Gluten", "Gluten", "");
        final ListOfQuestions question15 = new ListOfQuestions("The sprinkler system of irrigation is more useful for?", "Colling the crop", "Controlled water supply", "Sandy soils", "All the above", "All the above", "");

        //add all questions to List<ListOfQuestions>
        questionsLists.add(question1);
        questionsLists.add(question2);
        questionsLists.add(question3);
        questionsLists.add(question4);
        questionsLists.add(question5);
        questionsLists.add(question6);
        questionsLists.add(question7);
        questionsLists.add(question8);
        questionsLists.add(question9);
        questionsLists.add(question10);
        questionsLists.add(question11);
        questionsLists.add(question12);
        questionsLists.add(question13);
        questionsLists.add(question14);
        questionsLists.add(question15);

        return questionsLists;
    }

    public static List<ListOfQuestions> getQuestions(String selectedTopicName) {
        switch (selectedTopicName) {
            case "java":
                return javaQuestions();
            case "nursing":
                return nursingQuestions();
            case "sociology":
                return sociologyQuestions();
            case "physics":
                return physicsQuestions();
            case "farming":
                return farmingQuestions();
            case "civilEngineering":
                return civilEngineeringQuestions();
            default:
                return null;
        }
    }
}

